### PR TITLE
Adapt to coq/coq#8817 (SProp)

### PR DESCRIPTION
**Pull request by SkySkimmer**
Please wait before merging.

### CODE REVIEW

**Comment by ppedrot** [comment]
Please merge.

**Comment by ejgallego** [comment]
@SkySkimmer this needs a rebase.

**Comment by SkySkimmer** [comment]
Done

**Comment by ejgallego** [comment]
CI failed @SkySkimmer

**Comment by SkySkimmer** [comment]
The docker stuff hasn't updated yet

**Comment by ejgallego** [comment]
I guess you can re-push now @SkySkimmer

**Comment by ejgallego** [comment]
@lukaszcz CI green, please merge, thanks!

**Comment by ppedrot** [comment]
Ping, the Coq CI is waiting for this!

**Pull request merged**
